
file (COPY ${SRC} DESTINATION ${DST} FILES_MATCHING PATTERN "*.tex")
file (COPY ${SRC} DESTINATION ${DST} FILES_MATCHING PATTERN "*.bst")
file (COPY ${SRC} DESTINATION ${DST} FILES_MATCHING PATTERN "*.bib")
